apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: assignment3
type: Opaque
data:
  mysql_root_password: cm9vdHBhc3M=
  mysql_user: Zmxhc2t1c2Vy
  mysql_password: Zmxhc2twYXNz
  mysql_database: Zmxhc2tkYg==
